import { Amiri_Quran, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PrayersContextProvider } from "./Context/PrayerContext";
import { AuthProvider } from "./Context/UserContext";
import { AlertContextProvider } from "./Context/AlertContext";
import { ReciterProvider } from "./Context/RecitersContext";
import { WeatherProvider } from "./Context/WeatherContext";
import { HadithProvider } from "./Context/HadithContext";
import { QuranProvider } from "./Context/QuranContext";


const AmiriQuran = Amiri_Quran({
  variable: "--font-amiri-quran",
  subsets: ["latin"],
  weight : ["400"],
});

export const metadata = {
  title: "Islam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-[#0d1117] ${AmiriQuran.variable} font-sans antialiased`}
      >
        <AlertContextProvider>
          <AuthProvider>
            <ReciterProvider>
              <QuranProvider>
                <HadithProvider>
                  <WeatherProvider>
                    <PrayersContextProvider>
                      {children}
                    </PrayersContextProvider>
                  </WeatherProvider>
                </HadithProvider>
              </QuranProvider>
            </ReciterProvider>
          </AuthProvider>
        </AlertContextProvider>
      </body>
    </html>
  );
}
