import { Amiri_Quran, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PrayersContextProvider } from "./Context/PrayerContext";
import { AuthProvider } from "./Context/UserContext";
import { AlertContextProvider } from "./Context/AlertContext";
import { ReciterProvider } from "./Context/RecitersContext";


const AmiriQuran = Amiri_Quran({
  variable: "--font-amiri-quran",
  subsets: ["latin"],
  weight : ["400"],
});

export const metadata = {
  title: "Islam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-[#0d1117] ${AmiriQuran.variable} font-sans antialiased`}
      >
        <AlertContextProvider>
          <AuthProvider>
            <ReciterProvider>
              <PrayersContextProvider>
                {children}
              </PrayersContextProvider>
            </ReciterProvider>
          </AuthProvider>
        </AlertContextProvider>
      </body>
    </html>
  );
}
