import { Amiri_Quran, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PrayersContextProvider } from "./Context/PrayerContext";


const AmiriQuran = Amiri_Quran({
  variable: "--font-amiri-quran",
  subsets: ["latin"],
  weight : ["400"],
});

export const metadata = {
  title: "Islam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-[#0d1117] ${AmiriQuran.variable} font-sans antialiased`}
      >
        <PrayersContextProvider>
          {children}
        </PrayersContextProvider>
      </body>
    </html>
  );
}
